ユーザー登録機能
haruki00000000/twitter-clone-app pull request #1
Opened 2021-01-22 04:55 UTC by haruki00000000

ユーザー登録機能を作りました

2021-01-22 05:01 UTC, kpppn commented
不要なファイル `*.pyc` などもコミットに含まれてしまっているので.gitignoreの設定をまずお願いします

2021-01-26 08:31 UTC, kpppn requested changes
フロントエンドコース修了してるだけあって見た目は最高ですね
レビューしたので確認お願いします

2021-01-26 08:31 UTC, kpppn commented on mysite/polls/views.py
> +    template_name = "polls/home.html"
このページに認証なしで直接アクセスできてしまうので認証がなければアクセスできないよう設定してみてください

2021-01-26 08:31 UTC, kpppn commented on mysite/polls/views.py
> +        print(self.request.POST['next'])
このprintはデバッグ用かな？
不要であればレビュー依頼時は削除するようにしてください

2021-01-26 08:31 UTC, kpppn commented on mysite/polls/views.py
> +            form.save()
確認画面はnextの値で振り分けるのではなくformの送信先を/confirm等のURLに送信するようにしてください

2021-01-26 08:32 UTC, kpppn commented
ディレクトリ名がdjangoチュートリアルの名残？でpollsになってたりするのできたら修正してみてください

2021-01-29 02:09 UTC, haruki00000000 commented on mysite/polls/views.py
> +    template_name = "polls/home.html"
認証していない場合、一番最初のユーザ登録かログインかを選ぶ画面に飛ばしたいのですが、うまくいきません
いろいろ調べて、まねてみながらこのようにしたのですがどう改善すればいいでしょうか？
なにかヒントが欲しいです！

![スクリーンショット 2021-01-29 110751](https://user-images.githubusercontent.com/66406382/106222143-44f13280-6222-11eb-8746-051cd1beeddc.png)
![スクリーンショット 2021-01-29 110737](https://user-images.githubusercontent.com/66406382/106222140-43c00580-6222-11eb-9b93-cb26cc15610c.png)

2021-01-29 02:11 UTC, haruki00000000 commented on mysite/polls/views.py
> +        print(self.request.POST['next'])
分かりました！
癖づけておきます

2021-01-29 02:37 UTC, haruki00000000 commented on mysite/polls/views.py
> +            form.save()
すみません、あまりわからないです…
確認画面で修正・確定はこのnextで振り分けるのまでは大丈夫なのですが
formの送信先をどう分ければいいのでしょうか？
なにかヒントをいただけたらありがたいです

2021-01-29 04:52 UTC, kpppn commented on mysite/polls/views.py
> +    template_name = "polls/home.html"
login_url が空文字だとdjangoは何も設定されないと判定してデフォルトで設定されている `/accounts/login` にリダイレクトされてしまうと思います。

topページへリダイレクトしたい場合空文字ではなくルートを表す `/` を設定してみてください

2021-01-29 04:57 UTC, kpppn commented on mysite/polls/views.py
> +            form.save()
確認画面、登録処理のurlを別で用意するということです。
以下のサイトで紹介してることがやりたいことに近いと思います。
https://blog.narito.ninja/detail/45

さらにわからいことがあれば通話しましょう。気軽に呼んでください。

2021-01-30 04:43 UTC, kpppn approved these changes
lgtm

2021-01-31 00:28 UTC, merged