ツイート機能追加
haruki00000000/twitter-clone-app pull request #3
Opened 2021-02-09 02:41 UTC by haruki00000000

ツイート機能追加しました

2021-02-09 02:43 UTC, haruki00000000 commented
入力フォームが表示れないのですが、なにが問題なのかがわかりません。
いろいろ調べてみたのですが、どの資料を参考にしてもこれで動くと思うのですがなにが原因なのでしょうか？

![スクリーンショット 2021-02-09 113128](https://user-images.githubusercontent.com/66406382/107308497-1568e280-6acc-11eb-994a-f829fa4872ba.png)

2021-02-09 03:24 UTC, kpppn commented on mysite/twitter/views.py
> +        return render(request, 'Twitter/home.html', context)
ここの処理実行されてますか？

2021-02-10 01:37 UTC, haruki00000000 commented
adminサイトからDBに直接tweetを登録し、それをhtmlで出力できているので入力フォームで入れた内容がDBへ保存されればうまくいくと思うのですが、そのフォームの保存がなかなかできません。
調べてみたり、新規登録の時のコードを見てみましたがいまいちわかりません。
入力したフォームをDBへ保存するにはどのようなアクションが必要になりますか？

![スクリーンショット 2021-02-10 103438](https://user-images.githubusercontent.com/66406382/107452103-faf63e00-6b8b-11eb-89fa-f66d545f8d13.png)

2021-02-10 09:51 UTC, kpppn commented
ここは `form_class = TweetForm` の指定が必要です
https://github.com/haruki00000000/twitter-clone-app/pull/3/files#diff-8a7c72507ab952cff1a074ed5a87157f7dc08151c552d3c9c394c434a87e474cR58

ドキュメント：
https://docs.djangoproject.com/en/3.1/ref/class-based-views/generic-editing/#formview

2021-02-12 05:20 UTC, kpppn requested changes
確認お願いします

2021-02-12 05:20 UTC, kpppn commented on mysite/twitter/views.py
> +                if form.is_valid():
form_validメソッドへ処理が来てる次点で `form.is_valid` の条件が真になるので不要だと思います

2021-02-12 05:20 UTC, kpppn commented on mysite/twitter/views.py
> +            if self.request.method == 'POST':
このif文は必要ですか？

2021-02-12 05:21 UTC, kpppn commented
いまさらなんだけど `mysite/db.sqlite3` は.gitignoreに追加してほしいです

2021-02-15 02:02 UTC, kpppn approved these changes
lgtm

2021-02-15 02:12 UTC, merged