いいねボタンを追加
haruki00000000/twitter-clone-app pull request #5
Opened 2021-02-19 02:10 UTC by haruki00000000

いいねボタンを追加しました

2021-02-19 06:41 UTC, kpppn requested changes
確認ください

2021-02-19 06:41 UTC, kpppn commented on mysite/twitter/views.py
> +        print(tweet.like)
デバッグ用かな？

2021-02-19 06:41 UTC, kpppn commented on mysite/twitter/templates/twitter/home.html
> +                <a href="{% url 'twitter:like' tweet.pk %}" class="prev-like-btn"><i class="far fa-heart"></i><span class="like-num">{{tweet.like}}</span></a>
すでにいいねしてて押したらいいねの取り消しにするようにしてください

2021-02-19 06:41 UTC, kpppn commented on mysite/twitter/views.py
> +        tweet.save()
elseの中に入れる必要ないかな

2021-02-19 07:43 UTC, haruki00000000 commented
すでにいいねしているユーザーを削除したいのですが、そのユーザーのいいねしたことのみを削除ができません。
ユーザー自体が削除されたり、いいねを解除しようとするツイートが削除されます
また、いいねのツイートとユーザーの関係を作る（フォローの時のような）classを作ろうとも試みましたが、homeview内でtweetのidが取得できず特定ができませんでした。
HomeView内でuserとtweetをの関係性を一意にできれば、うまくできそうな気がするのですが…

![スクリーンショット 2021-02-19 163349](https://user-images.githubusercontent.com/66406382/108472831-98f6b080-72d0-11eb-9003-31389c075259.png)

![スクリーンショット 2021-02-19 164112](https://user-images.githubusercontent.com/66406382/108473417-58e3fd80-72d1-11eb-9e24-5b0500855fae.png)

2021-02-21 08:36 UTC, haruki00000000 commented
いいねを再度押すと、解除できるようになりました！

2021-02-21 09:10 UTC, haruki00000000 commented
質問があります
いいねを解除することはできましたが、すでにいいねを押しているときと押していないときで表示を変えたいです。
HomeViewでuser,tweetともに一致しているClassObjectの有無でcheckがTrue/Falseになるようにしたいのですが、ずっとFalseになってしまいます。
自分的にはうまくtweetの値が取れていないために、ずっと一致できていないのかなと思います。どうすればそれぞれに該当するtweetを取得できますか？
![スクリーンショット 2021-02-21 173808](https://user-images.githubusercontent.com/66406382/108620530-160c5c00-7470-11eb-893e-c2b832a0e551.png)
![スクリーンショット 2021-02-21 173847](https://user-images.githubusercontent.com/66406382/108620532-19074c80-7470-11eb-869b-53b3d882921a.png)

2021-02-21 09:12 UTC, haruki00000000 commented
また、gitignoreはうまくできていますでしょうか？
明示的にするというのは、調べたところでは必要なものをホワイトリストに入れていくという解釈をしました。

2021-02-22 02:04 UTC, haruki00000000 commented
一つをいいねすると、その他すべてがいいね済みの表示にされてしまいます。
contextdataのcheckを各ツイートごとに仕分けることはできませんか？

2021-02-22 02:08 UTC, kpppn commented
gitignoreの設定でさらに不要なファイルがコミットされてしまっている気がします

2021-02-22 02:10 UTC, kpppn commented
get_context_dataの中でlikeを押している一覧を取得し、テンプレートに渡すように変更し、html側の投稿のループの中でlikeが含まれているかの判断をすれば他の問題は解決されると思います

2021-02-22 03:10 UTC, haruki00000000 commented
どのようにして、likeの有無で条件分岐すればよいのでしょうか？
likeの一覧を渡して、likeをfor文で回すとその分いいねが増えてしまいます
![スクリーンショット 2021-02-22 121003](https://user-images.githubusercontent.com/66406382/108652207-ec524400-7506-11eb-8a9b-0f867f1b7fde.png)

![スクリーンショット 2021-02-22 120726](https://user-images.githubusercontent.com/66406382/108652122-b8771e80-7506-11eb-8245-66e752cdab2f.png)

2021-02-22 03:59 UTC, kpppn commented
likeをfor文で回さないやり方を考えてみてください

2021-02-25 05:22 UTC, kpppn requested changes
確認ください

2021-02-25 05:22 UTC, kpppn commented on mysite/twitter/views.py
> +    return redirect('twitter:home', pk=tweet.id)
follow/unfollowと同じようにこちらもlike/unlikeで分けてください

2021-02-25 05:22 UTC, kpppn commented on mysite/twitter/views.py
> +    is_like = Like.objects.filter(
is_likeだとブーリアンを表す変数っぽくなってしまってるので変更しましょう

2021-02-25 05:50 UTC, haruki00000000 commented on mysite/twitter/views.py
> +    is_like = Like.objects.filter(
わかりました！
しかし、like/unlikeを分けたことでlikeの数を数える必要がなくなり、temolate側で分岐できるようになったためis_likeに該当するものは今回削除しました。
今後、このことに気を付けたいと思います！

2021-02-25 05:59 UTC, kpppn requested changes
確認お願いします

2021-02-25 05:59 UTC, kpppn commented on mysite/twitter/views.py
> -    # like
ここの処理全て消したらurlに直接アクセスしたときに+1されちゃうのでされないように修正お願いします

2021-02-25 05:59 UTC, kpppn commented on mysite/twitter/views.py
> +    return redirect('twitter:home', pk=tweet.id)
このtweet.id付きのhomeとついてないhomeの違いってなに？

2021-02-25 06:18 UTC, haruki00000000 commented on mysite/twitter/views.py
> +    return redirect('twitter:home', pk=tweet.id)
urls.pyで、言い値を押した後のhomeへのurlが
    path('home/<int:pk>/', HomeView.as_view(), name='home'),
としていたので、そこに言い値をしたtweetのidをpkとして送ろうとしていました

2021-02-25 06:34 UTC, haruki00000000 commented
すみません、僕が直接URLにアクセスしてもなにも表示されないため分からなかったのですが修正してみました。
よろしくお願いします。

![image](https://user-images.githubusercontent.com/66406382/109112925-c0d98e80-777e-11eb-9d98-5446911eea32.png)

2021-02-25 06:37 UTC, kpppn commented
``/home/{id}/like` じゃないとだめよ
{id}はツイートのidに置き換えて

2021-02-25 06:43 UTC, haruki00000000 commented
合っていますでしょうか？
![スクリーンショット 2021-02-25 154213](https://user-images.githubusercontent.com/66406382/109113758-182c2e80-7780-11eb-9d98-28921f33a11f.png)
![スクリーンショット 2021-02-25 154156](https://user-images.githubusercontent.com/66406382/109113762-195d5b80-7780-11eb-9989-15f7a1a4dc4c.png)

2021-02-25 08:05 UTC, haruki00000000 commented
すみません、直接アクセスを防止する方法がわかりません。なにかヒントをいただければありがたいのですが…。
いつもヒントばかりいただいてすみません。
調べたところbefore_actionを設定する、デコレーターを自作する、postの時だけ動くように@require_POSTデコレーターを使用するなどを目にしました。
個人的に、@require_POSTを使うのがよさそうに感じたのですが、いいねボタンはformでないためpost methodが遅れません。
どうすればいいでしょうか？

2021-02-25 08:07 UTC, kpppn commented
直接のアクセスを防止する必要はないです
直接アクセスされてもシステムとして整合性が取れる（バグらない）ようになっていれば問題ありません

2021-02-25 08:25 UTC, haruki00000000 commented
> 直接のアクセスを防止する必要はないです
> 直接アクセスされてもシステムとして整合性が取れる（バグらない）ようになっていれば問題ありません

わかりました！

2021-03-01 04:11 UTC, kpppn approved these changes
lgtm

2021-03-01 08:54 UTC, merged